### ISSUE TITLE
Apprentices should demonstrate the ability to move a card each sprint

### ISSUE THREAD

**Issue by vleet** [PillarTechnology/guild-docs#13]
We often measure that we expect someone to be the driver of a one point card across the card wall.

**Comment by mcibulskis** [comment]
I don't think I would phrase it as "move a card each sprint".  Instead, I think I would phrase it as their, "being able to occasionally take the lead on playing a story that provides business value, seeing the story through from start to completion."

Similarly, adding in something for Journeymen for, "being able to consistently take the lead on playing a story that provides business value, seeing the story through from start to completion."

We should separate the ability to guide a card through to completion from the appropriate sizing of the story (which I think would fall more under story writing/prep/breakdown).
