### ISSUE TITLE
What are "marketable technologies"?

### ISSUE THREAD

**Issue by greghaskins** [PillarTechnology/guild-docs#15]
Maybe I just missed a link or something, but I can't seem to find a list and/or definition.

**Comment by vleet** [comment]
Marketable technologies are an interesting question:
- Is it something Pillar can sell?
- If you are world class at languages like J does that count?


As an organization we need someone that joins to be able to do something a project requires.  I believe that we have found that the more languages you know the faster to you are at learning a new one.

**Comment by blilley** [comment]
Maybe we can come up with a example set of Marketable technologies as it stands today?
We will of course have the refresh that list periodically as the world changes.
