### ISSUE TITLE
Master Craftsman - Exhibit All Behaviors of Craftsman

### ISSUE THREAD

**Issue by jameskbride** [PillarTechnology/guild-docs#19]
We should probably make it clear that a Master Craftsman should exhibit all of the behaviors of a Craftsman.  The way the document reads right now it sounds like they don't have to have had 6+ clients, 7+ years, 6+ 'marketable technologies', etc.

**Comment by jgartee** [comment]
I read the behaviors as being totally cumulative.  Further, I would advocate that the behaviors are continual and must be maintained to keep your standing.  In other words, once we reach the mountaintop there is no coasting.

As I stated elsewhere, I like the idea of peer reviews.  So, here I am a Craftsman.  Having been one for a year, am I _still_ mentoring Journeymen and Apprentices?  Am I _still_ speaking/blogging/OSS-ing?  Am I _still_ promoting good team practices on a day-to-day basis? If so, how effectively?  My peers should be the judge on an ongoing basis.

The same goes double for Master Craftsmen.  The emphasis changes, but not the commitment.
