### ISSUE TITLE
s/marketable technology/marketable skill/g

### ISSUE THREAD

**Issue by jimholmes** [PillarTechnology/guild-docs#30]
Focusing on marketable technology leaves off testers (<cough>me</cough>), PMs, and others who have roles not specifically tied to daily hands-on-keyboard coding. Emphasizing skills means we can, as appropriate, include tech as well as other domains.

**Comment by jgartee** [comment]
@jimholmes, I would disagree.  I believe that testers  bring incredible value and are, in fact, marketable technologies.  Knowing _where_, _how_, and _why_ to test effectively is at least as valuable as knowing how to write code.  As a developer myself, I find effective testing more challenging than the actual coding.

I would ask, if one cannot prove it will work, what good is it?

The same thing is true for the UX folks who use design and analytics to improve the customer experience through very subtle changes -- these can have massive impacts on gross sales on commerce sites, for example.
