### ISSUE TITLE
Tying persona behaviors to Pillar outcomes?

### ISSUE THREAD

**Issue by erikdietrich** [PillarTechnology/guild-docs#32]
One thing that I think would be interesting to see is an explicit mention of how each of the enumerated behaviors makes money for Pillar (i.e. the value story for Pillar of incurring incremental salary disbursement for person X to go from, say, Journeyman to Craftsman).

For instance, if I were running a software consultancy and hiring developers, the value of "knows more marketable technologies" is pretty clear.  If I have Alice, who knows 20 different techs, and Bob, who knows 3, Alice is better for my growth prospects and less likely to go devouring her own margins with bench time.

Unpopular as it may be to say due to its anti-meritocratic nature, "years of experience" is also easy to track this way.  The industry at large doesn't know how to measure competence very well and it latches onto "years of experience."  So it becomes easier on its face to convince clients to pay more for someone with a longer LinkedIn history.  Rightly or wrongly (and, wrongly, in my opinion), more clients will be more willing to pay high rates for someone that has 10 years of experience than someone that has 2.

It's likewise easy to make a case for mentoring and leadership and for emotional intelligence from a morale vs. attrition perspective alone. 

Some of the rest of the behaviors don't trigger me to make connections like this as easily, though.  Do clients care how many previous Pillar clients a consultant has worked with?  To the extent that this has any market value?  How about speaking and blogs?  Maintaining practice documents?  (I'm not disputing that these have value, per se -- just saying that the path to profit isn't as obvious, at least to me, since it probably takes a roundabout path through general brand promotion and the like)

Anyway, just an idea for something that could be an interesting thought exercise.  

Most orgs that employ developers have no idea how to articulate their value and just blindly reward people with COLAs for hanging around, whether they're even marginally productive or not.  It'd be cool to see a clear expression of, "these behaviors by developers demonstrably generate market value in the following ways, and so we reward developers who cultivate them accordingly."

**Comment by greghaskins** [comment]
Interesting point. I read these as a list of behaviors/skills that Pillar finds valuable, and you raise the important questions of why and how much. 

There's strategic value to many of these too, beyond what clients will see directly. Perhaps things like blogging, open source, and Pillar tenure (however you measure it) are something we incentivize as Pillar to help the company grow effectively (both people-wise and public-perception-wise).

**Comment by mstaffeld** [comment]
Duration awards sound an awful lot like a union and stagnation and complacency seem like a code smell in this industry. We should strive for more fun metrics like "Disruption Enablement Capability" or "Client Patience Demonstration" - but I guess those are soft skills that are also hard to measure and invaluable in a consulting role.

If the resources need the skills, where do those skills come from and who is responsible for enabling the future edification of said resources?
