### ISSUE TITLE
Client counts and time spent at each one

### ISSUE THREAD

**Issue by oshbec** [PillarTechnology/guild-docs#33]
One of the things that we talk about is the need to rotate our people to different clients and projects on a regular basis.  While this is being addressed, we'll want to make sure this is squared away if client count is going to be a criterion for advancement.

If you're at a client for 18 months, it's conceivable that some of your peers may have worked in projects at multiple clients in the same time frame.

Working in a collection of different projects settings is key to your professional development, so I definitely support the presence of this in the personas.

We may also want to generalize this to *projects*.  This language is used at the Apprentice level whereas "Client" is used everywhere else.  This could account for working on multiple teams / projects at the same client.

**Comment by mcibulskis** [comment]
Related to https://github.com/PillarTechnology/guild-docs/issues/21 and https://github.com/PillarTechnology/guild-docs/issues/14
