### ISSUE TITLE
The why ?

### ISSUE THREAD

**Issue by bijurajan** [PillarTechnology/guild-docs#35]
Couple of points:
1. The why? Why problem are we solving by experimenting this new hierarchical structure? Most companies are moving away from traditional hierarchical structure to more flatter structure whereby jobs are decoupled from designations/roles. 
2. Since we are a consulting company, our roles are mostly dictated to what our client requirements are. Which means an apprentice could be doing the work of a Master craftsman and vise-versa. Pillar would ideally like everyone to be at the Master Craftsman/Craftsman level, thereby requiring a higher billable rate from clients. The customer is king for a consulting firm. 
3. How does the guild structure align with personal compensation? How do we align constantly ourselves with the market conditions?
4. To staff our projects, how do we make sure we have proper ratio of the various artisan groups? Or is that something we already do sub-consciously?

**Comment by mstaffeld** [comment]
Great questions. This almost feels reactive when we look at what other exciting companies have already done. Where should we be on the culture curve? Should we be challenging ourselves to go beyond and achieve what we don't think we can? Even big bad Microsoft got rid of stack ranking. I think we can do something different and should inspire that sort of mentality and forward thinking. IMHO.

**Comment by mcibulskis** [comment]
Related to:
https://github.com/PillarTechnology/guild-docs/issues/21#issuecomment-162151815
