### ISSUE TITLE
Who is the target? 

### ISSUE THREAD

**Issue by mstaffeld** [PillarTechnology/guild-docs#36]
If we are talking about this for an evolutionary growth path through Pillar this seems to not hold much value to me. I love working on Pillar teams because there is not a perceived ranking and have never had to think about titles on the teams that I have been on. There is no feeling of 'the architects have spoken!' and there is not really a place for it IMHO when the teams work. 

If the progression is observed outside of the organization, will the vanity titles mean anything? For instance, if I am a Chuck Norris for 10 years, is that perceived as stagnation?

DetroitLabs started with a very flat structure and heard they were trying to do something differently, but I would be interested to see if we could reach out to them for some advice.

**Comment by mcibulskis** [comment]
Related to: https://github.com/PillarTechnology/guild-docs/issues/21#issuecomment-162151815
