### ISSUE TITLE
Questions and Responses. Who is making the final call on this?

### ISSUE THREAD

**Issue by bentidman** [PillarTechnology/guild-docs#38]
I see a lot of great concerns being raised here, and some great responses. I don't know however who has the final say in this. Are the people making the decision actively reading and responding to these issues? There is great stuff here and I want to make sure it's being heard. Come someone responsible for implementing this please speak to that?

**Comment by mholtman** [comment]
The definitions are open for comment until this Friday. After Friday, all of the questions will be aggregated and then answered in FAQ format the group that put them together. You can expect a final version of the definitions and the FAQ to be published in the next two weeks, before the holiday break.

**Comment by mholtman** [comment]
In case anyone is monitoring, we're still working on aggregating all of the feedback and questions that were posed. Stay tuned for an update early next week.
