### ISSUE TITLE
Artisans should have masterpieces.

### ISSUE THREAD

**Issue by rjo1970** [PillarTechnology/guild-docs#42]
An Artisan-level developer should have an open-source, personal, or Pillar-owned project which demonstrates a deep level of technical understanding and experience.

**Comment by jgartee** [comment]
Wow, this is an excellent idea.  It could be something required for even being __*considered*__ applying for Master Craftsman, and could take one of many forms (code, presentation series, etc.).

**Comment by mcresmenblock** [comment]
Or perhaps content in StepItUp showing deep knowledge and providing learning opportunities for others.
