### ISSUE TITLE
Understanding of business/delivery practices

### ISSUE THREAD

**Issue by jfolkerth** [PillarTechnology/guild-docs#43]
I propose adding a requirement about knowing how Pillar's business works, specifically from the delivery side. In particular, while artisans don't always get involved in contract negotiations, I feel it is important for us to understand how the negotiation process works, what a contract looks like, how the politics/legalities from it can affect our development teams, and how Pillar actually gets paid. It doesn't have to be a deep level of knowledge, though I would expect a master craftsman to know more than a journeyman, but it helps in maintaining a positive client relationship and for recognizing opportunities and threats in the industry. Since I've seen delivery leads become artisans and vice-versa, it also makes us more flexible and shrinks the distance between our delivery and technical sides.

**Comment by jgartee** [comment]
:+1:
