### ISSUE TITLE
FAQ suggestion

### ISSUE THREAD

**Issue by udioeater** [PillarTechnology/guild-docs#50]
I would like to offer an alternate answer to the following item listed on the FAQ:

> Related, is there a difference in the kind of talent for Forge dwellers and embedded consultants? Issue #31  [That is an interesting notion]
> I didn’t know we hired for two different types of engineers. In short, no, no there isn’t.

Suggested answer: 
In short, no. Although different skill sets may be required day-to-day while working in the Forge vs. at a client site, our goal is that any of our artisans should have the skill sets necessary to work effectively in either environment as needed.

**Comment by rdammkoehler** [comment]
Since there is no plus-1 on github, I'll just chime in and say I like Kevin's words

**Comment by mholtman** [comment]
Love the words, @udioeater. Can I persuade you to open a pull request with that change?

**Comment by udioeater** [comment]
I think you just did. :) Expect a pull request shortly.
