### ISSUE TITLE
Process of Moving Up in the Artisan Personas

### ISSUE THREAD

**Issue by amast09** [PillarTechnology/guild-docs#8]
- How does the process of moving up a persona become initiated?
- Who will judge a prospects ```behaviors```?
- How will the ```behaviors``` be judged (checked off) since some are subjective?

I know my questions may not have answers now, just inquiring to get a better idea of how everything will work or what some of the ideas currently are as to how it will work.

Thanks! :palm_tree: 

Aaron

**Comment by jgartee** [comment]
Keeping it DRY, see my comment on #19 

Further, I am in favor of the @mholtman approach...make it a big freakin' deal!  This would go double as a manifestation of a peer review process.  I may not care what a lot of people think, but I care __deeply__ what my peers at Pillar think.
